---
NONMEM_directory: /home/ali/nm760
NONMEM_version: 7.6
PsN_version: 5.6.0
command_line: /usr/local/bin/scmplus run02back.scm -dir=scm_run02_filtered -fast
common_options:
  abort_on_fail: 0
  accepted_ofv_difference: 0.5
  add_retries: 0
  always_datafile_in_nmrun: 0
  check_nmtran: 0
  clean: 2
  compress: 0
  crash_restarts: 1
  debug_rmd: 0
  degree: 0.1
  directory: /home/ali/Documents/GitHub/Modelling-project/scm_run02_filtered/rundir/
  display_iterations: 0
  handle_crashes: 0
  handle_msfo: 0
  html: 0
  large_omega_cv_limit: 0.8
  large_sigma_cv_limit: 0.8
  large_theta_cv_limit: 0.5
  last_est_complete: 0
  lsf_sleep: 3
  min_retries: 0
  missing_data_token: -99
  model_subdir: 0
  nice: 19
  nm_output: 'ext,cov,cor,coi,phi,phm,cnv,smt,rmt,npd,npe,npi,npl,ets'
  nm_version: default
  nmfe: 1
  nodes: 0
  pdf: 1
  picky: 0
  prepend_model_file_name: 0
  quick_summarize: 0
  retries: 1
  rmarkdown: 1
  rplots: 0
  run_on_lsf: 0
  run_on_sge: 0
  run_on_slurm: 0
  run_on_torque: 0
  run_on_ud: 0
  run_on_zink: 0
  seed: 130162
  send_email: 0
  shrinkage: 0
  significant_digits_accept: 0
  so: 0
  template_directory_rplots: /usr/local/share/perl5/5.40/PsN_5_6_0/R-scripts
  template_file_rplots: scmplus_default.R
  threads: 6
  tweak_inits: 1
  verbose: 0
  zip: 1
model_files:
  - /home/ali/Documents/GitHub/Modelling-project/run02.mod
start_time: 2026-01-04 13:16:05
tool_name: scmplus
tool_options:
  epsilon: 1
  foce: 1
  global_init: 0.001
  gof: p_value
  linearize: 0
  logfile: /home/ali/Documents/GitHub/Modelling-project/scm_run02_filtered/scmlog.txt
  noabort: 0
  only_successful: 0
  p_backward: 0.01
  p_value: 0.05
  parallel_states: 0
  search_direction: forward
  update_derivatives: 0
