---
NONMEM_directory: /home/ali/nm760
NONMEM_version: 7.6
PsN_version: 5.6.0
command_line: /usr/local/bin/execute run04.mod
common_options:
  abort_on_fail: 0
  accepted_ofv_difference: 0.5
  add_retries: 0
  always_datafile_in_nmrun: 0
  check_nmtran: 0
  clean: 3
  compress: 0
  crash_restarts: 5
  debug_rmd: 0
  degree: 0.1
  directory: /home/ali/Documents/GitHub/Modelling-project/modelfit_dir18/
  display_iterations: 1
  handle_crashes: 1
  handle_msfo: 0
  html: 0
  large_omega_cv_limit: 0.8
  large_sigma_cv_limit: 0.8
  large_theta_cv_limit: 0.5
  last_est_complete: 0
  lsf_sleep: 3
  min_retries: 0
  missing_data_token: -99
  model_subdir: 0
  nice: 19
  nm_output: 'ext,cov,cor,coi,phi,phm,cnv,smt,rmt,npd,npe,npi,npl,ets'
  nm_version: default
  nmfe: 1
  nodes: 0
  pdf: 1
  picky: 0
  prepend_model_file_name: 0
  quick_summarize: 0
  retries: 0
  rmarkdown: 1
  rplots: 0
  run_on_lsf: 0
  run_on_sge: 0
  run_on_slurm: 0
  run_on_torque: 0
  run_on_ud: 0
  run_on_zink: 0
  seed: 243199
  send_email: 0
  shrinkage: 0
  significant_digits_accept: 0
  so: 0
  template_directory_rplots: /usr/local/share/perl5/5.40/PsN_5_6_0/R-scripts
  template_file_rplots: execute_default.Rmd
  threads: 5
  tweak_inits: 1
  verbose: 0
  zip: 1
copied_files:
  - run04.lst
  - run04.ext
  - run04.phi
  - run04_sdtab
  - run04_patab
  - run04_catab
  - run04_cotab
finish_time: 2025-12-22 15:10:44
model_files:
  - /home/ali/Documents/GitHub/Modelling-project/run04.mod
start_time: 2025-12-22 15:10:27
tool_name: execute
tool_options:
  copy_data: 1
  prepend_options_to_lst: 0
  tail_output: 0
