---
NONMEM_directory: /home/ali/nm760
NONMEM_version: 7.6
PsN_version: 5.6.0
command_line: /usr/local/bin/vpc -samples=1000 -auto_bin=auto -dir=vpc_run15 -lloq=1 -dv=CONC_M7 -idv=TAD -nozip run16.mod
common_options:
  abort_on_fail: 0
  accepted_ofv_difference: 0.5
  add_retries: 0
  always_datafile_in_nmrun: 0
  check_nmtran: 0
  clean: 3
  compress: 0
  crash_restarts: 4
  debug_rmd: 0
  degree: 0.1
  directory: /home/ali/Documents/GitHub/Modelling-project/vpc_run15/
  display_iterations: 0
  handle_crashes: 1
  handle_msfo: 0
  html: 0
  large_omega_cv_limit: 0.8
  large_sigma_cv_limit: 0.8
  large_theta_cv_limit: 0.5
  last_est_complete: 0
  lsf_sleep: 3
  min_retries: 0
  missing_data_token: -99
  model_subdir: 0
  nice: 19
  nm_output: 'ext,cov,cor,coi,phi,phm,cnv,smt,rmt,npd,npe,npi,npl,ets'
  nm_version: default
  nmfe: 1
  nodes: 0
  pdf: 1
  picky: 0
  prepend_model_file_name: 0
  quick_summarize: 0
  retries: 0
  rmarkdown: 1
  rplots: 0
  run_on_lsf: 0
  run_on_sge: 0
  run_on_slurm: 0
  run_on_torque: 0
  run_on_ud: 0
  run_on_zink: 0
  seed: 450881
  send_email: 0
  shrinkage: 0
  significant_digits_accept: 0
  so: 0
  template_directory_rplots: /usr/local/share/perl5/5.40/PsN_5_6_0/R-scripts
  template_file_rplots: vpc_default.Rmd
  threads: 5
  tweak_inits: 1
  verbose: 0
  zip: 0
model_files:
  - /home/ali/Documents/GitHub/Modelling-project/run16.mod
start_time: 2026-01-08 23:28:10
tool_name: vpc
tool_options:
  bin_array: ''
  boxcox_lambda: 0
  confidence_interval: 95
  copy_data: 1
  dv: CONC_M7
  fine_pi: 0
  flip_comments: 0
  idv: TAD
  in_filter: ''
  keep_estimation: 0
  levels: ''
  lloq: 1
  lnDV: 0
  mix: 0
  n_simulation_models: 1
  noprediction: 0
  offset_rawres: 1
  predcorr: 0
  refcorr_idv: 0
  sim_table: ''
  so: 0
  varcorr: 0
